### ISSUE TITLE
Beschreibung zu Hub-Seite hinzufügen

### ISSUE THREAD

**Issue by harmoniemand** [makervsvirus/maker-vs-virus-theme-v2#26]

**Comment by harmoniemand** [comment]
Lennart Thamm Gestern um 20:29 Uhr

Inhalt in etwa:
"Um ein Produkt anzufragen, nimm Kontakt zu einem Hub auf. Sie koordinieren die Produktion und Auslieferung mit allen bei uns registrierten Makern. Suche dazu in der Karte oder der Tabelle weiter unten einen Hub in deiner Nähe."

Position: Seite "Alle Hubs" direkt am Anfang über der Karte

**Comment by lthamm** [comment]
Ist online
