### ISSUE TITLE
Suche für DataTables über alle Felder (vor allem PLZ, Ort, Bundesland)

### ISSUE THREAD

**Issue by harmoniemand** [makervsvirus/maker-vs-virus-theme-v2#29]

**Comment by harmoniemand** [comment]
Lennart Thamm Gestern um 20:21 Uhr

Die Suche funktioniert immer über alle Felder, PLZ und Bundesland fehlten in den Daten, habe sie jetzt in den letzten 2 Commits dazu genommen und in einer Spalte mit Ort angezeigt. Kann sein, dass es optisch noch überarbeitet werden muss

**Comment by lthamm** [comment]
Ist mit dem letzten Merge in Master online gegangen
